@HOST = http://localhost:8080

GET {{HOST}}

###

POST {{HOST}}/extract
Content-Type: application/json
# X-Debug-Show-Prompts: 

{
    "model": "llama",
    "products": [
        {
            "description": "Baignoire d'angle Geberit Bastia avec pieds: 142x142cm",
            "fields_to_extract": [
                "EF000040",
                "EF000008",
                "EF001438",
                "EF001257",
                "EF000010",
                "EF024897",
                "EF000007",
                "EF002169"
            ]
        }
    ]
}